controller_list:
  - name: fake_manipulator_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_robotiq_controller
    joints:
      - l_palm_finger_1_joint
      - l_finger_1_joint_1
      - l_finger_1_joint_2
      - l_finger_1_joint_3
      - l_finger_1_joint_paradistal_hinge
      - l_finger_1_joint_median_actuating_hinge
      - l_finger_1_joint_median_actuating_hinge_median_bar
      - l_finger_1_joint_paramedian_hinge
      - l_finger_1_joint_paramedian_hinge_median_bar_underactuated
      - l_finger_1_joint_paraproximal_actuating_hinge
      - l_finger_1_joint_paraproximal_bar
      - l_finger_1_joint_proximal_actuating_hinge
      - l_finger_1_joint_proximal_actuating_bar
      - l_palm_finger_2_joint
      - l_finger_2_joint_1
      - l_finger_2_joint_2
      - l_finger_2_joint_3
      - l_finger_2_joint_paradistal_hinge
      - l_finger_2_joint_median_actuating_hinge
      - l_finger_2_joint_median_actuating_hinge_median_bar
      - l_finger_2_joint_paramedian_hinge
      - l_finger_2_joint_paramedian_hinge_median_bar_underactuated
      - l_finger_2_joint_paraproximal_actuating_hinge
      - l_finger_2_joint_paraproximal_bar
      - l_finger_2_joint_proximal_actuating_hinge
      - l_finger_2_joint_proximal_actuating_bar
      - l_palm_finger_middle_joint
      - l_finger_middle_joint_1
      - l_finger_middle_joint_2
      - l_finger_middle_joint_3
      - l_finger_middle_joint_paradistal_hinge
      - l_finger_middle_joint_median_actuating_hinge
      - l_finger_middle_joint_median_actuating_hinge_median_bar
      - l_finger_middle_joint_paramedian_hinge
      - l_finger_middle_joint_paramedian_hinge_median_bar_underactuated
      - l_finger_middle_joint_paraproximal_actuating_hinge
      - l_finger_middle_joint_paraproximal_bar
      - l_finger_middle_joint_proximal_actuating_hinge
      - l_finger_middle_joint_proximal_actuating_bar